Work around conflicting identifiers in C
Recent revisions of C++ support UTF-8, UTF-16 and UTF-32 literals:
https://en.cppreference.com/w/cpp/language/string_literal

Since the UTF-16 and UTF-32 literals only differ in case,
they produce the same identifiers:

src/Language/C/AST.hs:5543:1: error:
    Multiple declarations of ‘AnonymousUDQuote’
    Declared at: src/Language/C/AST.hs:4694:1
                 src/Language/C/AST.hs:5543:1
     |
5543 | type AnonymousUDQuote = AST.Token.Token "u\"" 114
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/C/AST.hs:5545:1: error:
    Multiple declarations of ‘AnonymousUSQuote’
    Declared at: src/Language/C/AST.hs:4696:1
                 src/Language/C/AST.hs:5545:1
     |
5545 | type AnonymousUSQuote = AST.Token.Token "u'" 108
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^